HELLO-MICROVERSE PROJECT-1
Nowembabazi/HELLO-MICROVERSE pull request #1
Opened 2022-08-17 17:47 UTC by Nowembabazi

# In this project, I achieved the following;
- I added linter files
- I added test.md file into the .gitignore
- I created index.html file
- I created styles.css and linked it with index.html file.
- I used gitflow to create branch-1

2022-08-17 18:01 UTC, ichala requested changes
Hi @Nowembabazi , 

Good job so far! 👏👏👏
There are some issues that you still need to work on to go to the next project but you're almost there!

![the-simpsons-homer-simpson](https://user-images.githubusercontent.com/28307960/157369993-50d5ba12-099f-4f2a-9a19-5e57ee2d1c96.gif)

## To Highlight 🎉

- Correct Readme template. ✔️
- No Linters Errors ✔️
- PR has a good title and summary ✔️

 ## Required Changes ♻️
 
- [ ]  _**_Check The Comments Below_**_

## Optional suggestions
 - [ ] [OPTIONAL] Branch should have a name of a feature or action (e.g. 'created_sidebar' or 'added_comments_section'). kindly try to apply that in your future projects! otherwise great job again you did a great effort

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag  @ichala in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-17 18:01 UTC, ichala commented on README.md
> +_NOTE: we recommend using the [MIT license](https://choosealicense.com/licenses/mit/) - you can set it up quickly by [using templates available on GitHub](https://docs.github.com/en/communities/setti
- [ ] Great job using the perfect readme template 💯 , kindly fix your license link because it's broken

2022-08-17 18:01 UTC, ichala commented on test.md
> +This should be ignored by git.
- [ ] this file shouldn't be in your repo, I think it's here because you created it before listing it in .gitignore file, kindly remove it manually and push your commit

2022-08-17 18:01 UTC, ichala commented on README.md
> +[Live Demo Link](https://livedemo.com)
- [ ] kindly remove this section since you have no live demo link yet

2022-08-17 19:36 UTC, ichala approved these changes
Hi @Nowembabazi  ,
# Status: Approved :heavy_check_mark: :heavy_check_mark: :heavy_check_mark:  

 
![68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f6c3366516333614356304871707a5763552f67697068792e676966](https://user-images.githubusercontent.com/85113567/184604589-430cf4bc-1d2e-4603-976a-7a48a899ea35.gif)

# To Highlight 💪🏻
✅ You used the correct Github Flow.
✅ Professional README.
✅ No Linters errors.
✅ .gitignore looks great.


Good job implementing the required changes :+1: Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
*************************************
# Optional Suggestions 

- [ ] [OPTIONAL] Branch should have a name of a feature or action (e.g. 'created_sidebar' or 'added_comments_section'). kindly try to apply that in your future projects ! otherwise great job again you did a great effort



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-18 06:30 UTC, merged

2022-08-19 09:12 UTC, prolajumokeoni reviewed
Hi @Nowembabazi  

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a wrong project

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._